name: Rust Project CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: cargo build --release

      - name: Tag new version
        id: tag_version
        if: github.ref == 'refs/heads/main'
        uses: anothrNick/github-tag-action@1.36.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
          release_branches: main

      - name: Publish to crates.io
        if: github.ref == 'refs/heads/main' && steps.tag_version.outputs.new_tag != ''
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
